ALTER TABLE [T_CHART_ACCOUNTS]
    DROP CONSTRAINT [UK_o08um0m6h78owqa4fhnnbpw0b]
GO
ALTER TABLE [T_CHART_ACCOUNTS]
    ADD CONSTRAINT
        [UniqueCodeChartAccounts] UNIQUE NONCLUSTERED ([CA_DELETED_TOKEN] ASC, [CA_CODE] ASC)
GO