/****** Object:  Table [dbo].[hibernate_sequences]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hibernate_sequences](
	[sequence_name] [varchar](255) NOT NULL,
	[sequence_next_hi_value] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[sequence_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ACCOUNT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ACCOUNT](
	[AC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AC_CODE] [int] NULL,
	[AC_CREDIT_OPENING] [numeric](19, 2) NULL,
	[AC_DEBIT_OPENING] [numeric](19, 2) NULL,
	[AC_DELETED_TOKEN] [binary](255) NULL,
	[AC_IS_DELETED] [bit] NULL,
	[AC_LABEL] [varchar](255) NULL,
	[AC_IS_LITRABLE] [bit] NULL,
	[AC_IS_RECONCILABLE] [bit] NULL,
	[AC_TIERS_ID] [bigint] NULL,
	[AC_PLAN_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[AC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ACCOUNTING_CONFIGURATION]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ACCOUNTING_CONFIGURATION](
	[AC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AC_DELETED_TOKEN] [binary](255) NULL,
	[AC_IS_DELETED] [bit] NULL,
	[AC_AMORTIZATION_ACCOUNT_ID] [bigint] NULL,
	[AC_BALANCE_SHEET_CLOSING_ACCOUNT_ID] [bigint] NULL,
	[AC_BALANCE_SHEET_OPENNING_ACCOUNT_ID] [bigint] NULL,
	[AC_BANK_ACCOUNTING_ACCOUNT_ID] [bigint] NULL,
	[AC_COFFER_ACCOUNTING_ACCOUNT_ID] [bigint] NULL,
	[AC_CURRENT_FISCAL_YEAR_ID] [bigint] NULL,
	[AC_CUSTOMER_ACCOUNT_ID] [bigint] NULL,
	[AC_H_TAX_PURCHASES_ACCOUNT_ID] [bigint] NULL,
	[AC_H_TAX_SALES_ACCOUNT_ID] [bigint] NULL,
	[AC_IMMOBILIZATION_ACCOUNT_ID] [bigint] NULL,
	[AC_JOURNAL_A_NEW_ID] [bigint] NULL,
	[AC_JOURNAL_BANK_ID] [bigint] NULL,
	[AC_JOURNAL_COFFER_ID] [bigint] NULL,
	[AC_JOURNAL_PURCHASES_ID] [bigint] NULL,
	[AC_JOURNAL_SALES_ID] [bigint] NULL,
	[AC_RESULT_ACCOUNT_ID] [bigint] NULL,
	[AC_SUPPLIER_ACCOUNT_ID] [bigint] NULL,
	[AC_TAX_PURCHASES_ACCOUNT_ID] [bigint] NULL,
	[AC_TAX_SALES_ACCOUNT_ID] [bigint] NULL,
	[AC_TAX_STAMP_ACCOUNTING_ACCOUNT_PURCHASE] [bigint] NULL,
	[AC_TAX_STAMP_ACCOUNTING_ACCOUNT_SALES] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[AC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_AMORTIZATION_TABLE]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_AMORTIZATION_TABLE](
	[AT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AT_ACQUISITION_VALUE] [numeric](19, 3) NULL,
	[AT_ANNUITY_EXERCISE] [numeric](19, 3) NULL,
	[AT_DELETED_TOKEN] [binary](255) NULL,
	[AT_IS_DELETED] [bit] NULL,
	[AT_PREVIOUS_DEPRECIATION] [numeric](19, 3) NULL,
	[AT_VCN] [numeric](19, 3) NULL,
	[AT_ASSETS_ID] [bigint] NULL,
	[AT_YEAR_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[AT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_BANK_RECONCILIATION_STATEMENT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT](
	[BRS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BRS_CLOSE_MONTH] [int] NULL,
	[BRS_DELETED_TOKEN] [binary](255) NULL,
	[BRS_FINAL_AMOUNT] [numeric](19, 2) NULL,
	[BRS_INITIAL_AMOUNT] [numeric](19, 2) NULL,
	[BRS_IS_DELETED] [bit] NULL,
	[BRS_ACCOUNT_ID] [bigint] NULL,
	[BRS_FISCAL_YEAR_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[BRS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_BILL_DOCUMENT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_BILL_DOCUMENT](
	[BD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BD_CREATION_DATE] [datetime2](7) NULL,
	[BD_DELETED_TOKEN] [binary](255) NULL,
	[BD_BILL_ID] [bigint] NULL,
	[BD_IS_DELETED] [bit] NULL,
	[BD_DOCUMENT_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[BD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_s0l261ekompwdk4ni0998hmfn] UNIQUE NONCLUSTERED 
(
	[BD_BILL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_CHART_ACCOUNTS]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_CHART_ACCOUNTS](
	[CA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CA_CODE] [int] NOT NULL,
	[CA_DELETED_TOKEN] [binary](255) NULL,
	[CA_IS_DELETED] [bit] NULL,
	[CA_LABEL] [varchar](255) NULL,
	[CA_TO_BALANCED] [bit] NULL,
	[CA_PARENT_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_o08um0m6h78owqa4fhnnbpw0b] UNIQUE NONCLUSTERED 
(
	[CA_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DEPRECIATION_ASSETS]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DEPRECIATION_ASSETS](
	[DA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DA_AMOUNT_CESSION] [numeric](19, 2) NULL,
	[DA_CESSION] [bit] NULL,
	[DA_DATE_CESSION] [datetime2](7) NULL,
	[DA_DELETED_TOKEN] [binary](255) NULL,
	[DA_ID_ASSETS] [bigint] NULL,
	[DA_IS_DELETED] [bit] NULL,
	[DA_AMORTIZATION_ACCOUNT_ID] [bigint] NULL,
	[DA_IMMOBILIZATION_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION](
	[DC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DC_DELETED_TOKEN] [binary](255) NULL,
	[DC_DEPRECIATION_PERIOD] [int] NULL,
	[DC_ID_CATEGORY] [bigint] NULL,
	[DC_IS_DELETED] [bit] NULL,
	[DC_AMORTIZATION_ACCOUNT_ID] [bigint] NULL,
	[DC_IMMOBILIZATION_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DOCUMENT_ACCOUNT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DOCUMENT_ACCOUNT](
	[DA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DA_CODE_DOCUMENT] [varchar](255) NULL,
	[DA_CREATION_DOCUMENT_DATE] [datetime2](7) NULL,
	[DA_DELETED_TOKEN] [binary](255) NULL,
	[DA_DOCUMENT_DATE] [datetime2](7) NULL,
	[DA_IS_CREATED_FROM_MOVING_TO_NEXT_FISCAL_YEAR] [bit] NULL,
	[DA_IS_DELETED] [bit] NULL,
	[DA_IS_IMPORTED] [bit] NULL,
	[DA_LABEL] [varchar](255) NULL,
	[DA_STATUS] [varchar](255) NULL,
	[DA_FISCAL_YEAR_ID] [bigint] NULL,
	[DA_JOURNAL_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DOCUMENT_ACCOUNT_ATTACHEMENT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DOCUMENT_ACCOUNT_ATTACHEMENT](
	[DAA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DAA_DELETED_TOKEN] [binary](255) NULL,
	[DAA_FILE_NAME] [varchar](255) NULL,
	[DAA_IS_DELETED] [bit] NULL,
	[DAA_DOCUMENT_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DAA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DOCUMENT_ACCOUNT_LINE]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE](
	[DAL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DAL_CREDIT_AMOUNT] [numeric](19, 2) NULL,
	[DAL_DEBIT_AMOUNT] [numeric](19, 2) NULL,
	[DAL_DELETED_TOKEN] [binary](255) NULL,
	[DAL_DOCUMENT_LINE_DATE] [datetime2](7) NULL,
	[DAL_IS_CLOSE] [bit] NULL,
	[DAL_IS_DELETED] [bit] NULL,
	[DAL_LABEL] [varchar](255) NULL,
	[DAL_LETTER] [varchar](255) NULL,
	[DAL_RECONCILIATION_DATE] [date] NULL,
	[DAL_REFERENCE] [varchar](255) NULL,
	[DAL_ACCOUNT_ID] [bigint] NULL,
	[DAL_DOCUMENT_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[DAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_FISCAL_YEAR]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FISCAL_YEAR](
	[FY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FY_CLOSING_STATE] [int] NULL,
	[FY_CONCLUSION_DATE] [datetime2](7) NULL,
	[FY_DELETED_TOKEN] [binary](255) NULL,
	[FY_END_DATE] [datetime2](7) NULL,
	[FY_IS_DELETED] [bit] NULL,
	[FY_NAME] [varchar](255) NULL,
	[FY_START_DATE] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[FY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_626mkrauwi22wi3te3irqt8uk] UNIQUE NONCLUSTERED 
(
	[FY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_FISCAL_YEAR_CLOSED_PERIODS]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FISCAL_YEAR_CLOSED_PERIODS](
	[FYC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FYC_DELETED_TOKEN] [binary](255) NULL,
	[FYC_END_DATE] [datetime2](7) NULL,
	[FYC_IS_DELELTED] [bit] NULL,
	[FYC_START_DATE] [datetime2](7) NULL,
	[FYC_FISCAL_YEAR_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[FYC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_GENERIC_ACCOUNT_RELATION]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_GENERIC_ACCOUNT_RELATION](
	[GAR_ID] [bigint] NOT NULL,
	[GAR_DELETED_TOKEN] [binary](255) NULL,
	[GAR_IS_DELETED] [bit] NULL,
	[GAR_RELATION_ENTITY_ID] [bigint] NULL,
	[GAR_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[GAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_JOURNAL]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_JOURNAL](
	[JN_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[JN_CODE] [varchar](255) NOT NULL,
	[JN_CREATED_DATE] [datetime2](7) NULL,
	[JN_DELETED_TOKEN] [binary](255) NULL,
	[JN_IS_DELETED] [bit] NULL,
	[JN_IS_MOVABLE] [bit] NULL,
	[JN_IS_RECONCILABLE] [bit] NULL,
	[JN_LABEL] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[JN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_48k0b0ocnhjwhh7ggcw6gacby] UNIQUE NONCLUSTERED 
(
	[JN_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_b5yybeg4eiufn90qpktu4x7yu] UNIQUE NONCLUSTERED 
(
	[JN_LABEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_REPORT_LINE]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_REPORT_LINE](
	[RL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RL_AMOUNT] [numeric](19, 2) NULL,
	[RL_ANNEX_CODE] [varchar](255) NULL,
	[RL_DELETED_TOKEN] [binary](255) NULL,
	[RL_FORMULA] [varchar](255) NULL,
	[RL_IS_DELETED] [bit] NULL,
	[RL_IS_MANUALLY_CHANGED] [bit] NULL,
	[RL_IS_NEGATIVE] [bit] NULL,
	[RL_LABEL] [varchar](255) NULL,
	[RL_LAST_UPDATED] [datetime2](7) NULL,
	[RL_LINE_INDEX] [varchar](255) NULL,
	[RL_REPORT_TYPE] [varchar](255) NULL,
	[RL_USER] [varchar](255) NULL,
	[RL_FISCAL_YEAR_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[RL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UKqcfk0jvmwi717pbgm3ylmh39v] UNIQUE NONCLUSTERED 
(
	[RL_FISCAL_YEAR_ID] ASC,
	[RL_LINE_INDEX] ASC,
	[RL_REPORT_TYPE] ASC,
	[RL_DELETED_TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_STANDARD_REPORT_LINE]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_STANDARD_REPORT_LINE](
	[SRL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SRL_ANNEX_CODE] [varchar](255) NULL,
	[SRL_DELETED_TOKEN] [binary](255) NULL,
	[SRL_FORMULA] [varchar](255) NULL,
	[SRL_IS_DELETED] [bit] NULL,
	[SRL_IS_NEGATIVE] [bit] NULL,
	[SRL_LABEL] [varchar](255) NULL,
	[SRL_LINE_INDEX] [varchar](255) NULL,
	[SRL_REPORT_TYPE] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SRL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UKtmx02fk0775x820ai1agb1vk7] UNIQUE NONCLUSTERED 
(
	[SRL_LINE_INDEX] ASC,
	[SRL_REPORT_TYPE] ASC,
	[SRL_DELETED_TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TEMPLATE_ACCOUNTING]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TEMPLATE_ACCOUNTING](
	[TA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TA_DELELTED_TOKEN] [binary](255) NULL,
	[TA_IS_DELETED] [bit] NULL,
	[TA_LABEL] [varchar](255) NULL,
	[TA_JOURNAL_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[TA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS](
	[TAD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TAD_CREDIT_AMOUNT] [numeric](19, 2) NULL,
	[TAD_DEBIT_AMOUNT] [numeric](19, 2) NULL,
	[TAD_DELETED_TOKEN] [binary](255) NULL,
	[TAD_IS_DELETED] [bit] NULL,
	[TAD_LABEL] [varchar](255) NULL,
	[TAD_ACCOUNT_ID] [bigint] NULL,
	[TAD_TEMPLATE_ACCOUNTING_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[TAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TJ_ACCOUNT_BANK]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TJ_ACCOUNT_BANK](
	[GAR_ID] [bigint] NOT NULL,
	[GAR_DELETED_TOKEN] [binary](255) NULL,
	[GAR_IS_DELETED] [bit] NULL,
	[GAR_RELATION_ENTITY_ID] [bigint] NULL,
	[GAR_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[GAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UKt1gbuojoo5no671s7un0j74kw] UNIQUE NONCLUSTERED 
(
	[GAR_DELETED_TOKEN] ASC,
	[GAR_RELATION_ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TJ_ACCOUNT_COFFER]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TJ_ACCOUNT_COFFER](
	[GAR_ID] [bigint] NOT NULL,
	[GAR_DELETED_TOKEN] [binary](255) NULL,
	[GAR_IS_DELETED] [bit] NULL,
	[GAR_RELATION_ENTITY_ID] [bigint] NULL,
	[GAR_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[GAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK7gduyeg0b9dj7eossgxym6hqm] UNIQUE NONCLUSTERED 
(
	[GAR_DELETED_TOKEN] ASC,
	[GAR_RELATION_ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TJ_ACCOUNT_CUSTOMER]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TJ_ACCOUNT_CUSTOMER](
	[GAR_ID] [bigint] NOT NULL,
	[GAR_DELETED_TOKEN] [binary](255) NULL,
	[GAR_IS_DELETED] [bit] NULL,
	[GAR_RELATION_ENTITY_ID] [bigint] NULL,
	[GAR_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[GAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UKip6ek3ju44d8vqijkw3gespgb] UNIQUE NONCLUSTERED 
(
	[GAR_DELETED_TOKEN] ASC,
	[GAR_RELATION_ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TJ_ACCOUNT_SUPPLIER]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TJ_ACCOUNT_SUPPLIER](
	[GAR_ID] [bigint] NOT NULL,
	[GAR_DELETED_TOKEN] [binary](255) NULL,
	[GAR_IS_DELETED] [bit] NULL,
	[GAR_RELATION_ENTITY_ID] [bigint] NULL,
	[GAR_ACCOUNT_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[GAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UKmch1ybfumwps0sbb5uy3w685s] UNIQUE NONCLUSTERED 
(
	[GAR_DELETED_TOKEN] ASC,
	[GAR_RELATION_ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TJ_PAYMENT_ACCOUNT]    Script Date: 01/02/2020 01:06:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TJ_PAYMENT_ACCOUNT](
	[PA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PA_DELETED_TOKEN] [binary](255) NULL,
	[PA_IS_DELETED] [bit] NULL,
	[PA_TAX_ID] [bigint] NULL,
	[PA_HTAX_PURCHASES_ACCOUNT] [bigint] NULL,
	[PA_HTAX_SALES_ACCOUNT] [bigint] NULL,
	[PA_TAX_PURCHASES_ACCOUNT] [bigint] NULL,
	[PA_TAX_SALES_ACCOUNT] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[PA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_ACCOUNT] ADD  DEFAULT ((0)) FOR [AC_IS_DELETED]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] ADD  DEFAULT ((0)) FOR [AC_IS_DELETED]
GO
ALTER TABLE [dbo].[T_AMORTIZATION_TABLE] ADD  DEFAULT ((0)) FOR [AT_IS_DELETED]
GO
ALTER TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT] ADD  DEFAULT ((0)) FOR [BRS_IS_DELETED]
GO
ALTER TABLE [dbo].[T_BILL_DOCUMENT] ADD  DEFAULT ((0)) FOR [BD_IS_DELETED]
GO
ALTER TABLE [dbo].[T_CHART_ACCOUNTS] ADD  DEFAULT ((0)) FOR [CA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS] ADD  DEFAULT ((0)) FOR [DA_CESSION]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS] ADD  DEFAULT ((0)) FOR [DA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION] ADD  DEFAULT ((0)) FOR [DC_IS_DELETED]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT] ADD  DEFAULT ((0)) FOR [DA_IS_CREATED_FROM_MOVING_TO_NEXT_FISCAL_YEAR]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT] ADD  DEFAULT ((0)) FOR [DA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT] ADD  DEFAULT ((0)) FOR [DA_IS_IMPORTED]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_ATTACHEMENT] ADD  DEFAULT ((0)) FOR [DAA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE] ADD  DEFAULT ((0)) FOR [DAL_IS_CLOSE]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE] ADD  DEFAULT ((0)) FOR [DAL_IS_DELETED]
GO
ALTER TABLE [dbo].[T_FISCAL_YEAR] ADD  DEFAULT ((0)) FOR [FY_CLOSING_STATE]
GO
ALTER TABLE [dbo].[T_FISCAL_YEAR] ADD  DEFAULT ((0)) FOR [FY_IS_DELETED]
GO
ALTER TABLE [dbo].[T_FISCAL_YEAR_CLOSED_PERIODS] ADD  DEFAULT ((0)) FOR [FYC_IS_DELELTED]
GO
ALTER TABLE [dbo].[T_GENERIC_ACCOUNT_RELATION] ADD  DEFAULT ((0)) FOR [GAR_IS_DELETED]
GO
ALTER TABLE [dbo].[T_JOURNAL] ADD  DEFAULT ((0)) FOR [JN_IS_DELETED]
GO
ALTER TABLE [dbo].[T_REPORT_LINE] ADD  DEFAULT ((0)) FOR [RL_IS_DELETED]
GO
ALTER TABLE [dbo].[T_STANDARD_REPORT_LINE] ADD  DEFAULT ((0)) FOR [SRL_IS_DELETED]
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING] ADD  DEFAULT ((0)) FOR [TA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS] ADD  DEFAULT ((0)) FOR [TAD_IS_DELETED]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_BANK] ADD  DEFAULT ((0)) FOR [GAR_IS_DELETED]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_COFFER] ADD  DEFAULT ((0)) FOR [GAR_IS_DELETED]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_CUSTOMER] ADD  DEFAULT ((0)) FOR [GAR_IS_DELETED]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_SUPPLIER] ADD  DEFAULT ((0)) FOR [GAR_IS_DELETED]
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT] ADD  DEFAULT ((0)) FOR [PA_IS_DELETED]
GO
ALTER TABLE [dbo].[T_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK9wan7m7rtbecm0skmhyjbqxy3] FOREIGN KEY([AC_PLAN_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNT] CHECK CONSTRAINT [FK9wan7m7rtbecm0skmhyjbqxy3]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK4krielsrbjjoceht8mdedg4c1] FOREIGN KEY([AC_TAX_STAMP_ACCOUNTING_ACCOUNT_PURCHASE])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FK4krielsrbjjoceht8mdedg4c1]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK6a67vl87gtjjr5vy8e2v49qln] FOREIGN KEY([AC_COFFER_ACCOUNTING_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FK6a67vl87gtjjr5vy8e2v49qln]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK6eqxkh0xcmgtncuqtui8dcv3u] FOREIGN KEY([AC_JOURNAL_BANK_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FK6eqxkh0xcmgtncuqtui8dcv3u]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK92xtxumicppbn5xurukwfq8vx] FOREIGN KEY([AC_RESULT_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FK92xtxumicppbn5xurukwfq8vx]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKbbpjmynsd3o149efpxh8ja0s7] FOREIGN KEY([AC_JOURNAL_A_NEW_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKbbpjmynsd3o149efpxh8ja0s7]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKdbw00yomg44p9r9x4o30db6vd] FOREIGN KEY([AC_TAX_STAMP_ACCOUNTING_ACCOUNT_SALES])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKdbw00yomg44p9r9x4o30db6vd]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKfq5lmjce8vfsg4f1dh07ehshb] FOREIGN KEY([AC_CURRENT_FISCAL_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKfq5lmjce8vfsg4f1dh07ehshb]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKhboj4itxalcopw9e530tghica] FOREIGN KEY([AC_SUPPLIER_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKhboj4itxalcopw9e530tghica]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKhhclhc3q32feengo84nnqwmdm] FOREIGN KEY([AC_BALANCE_SHEET_OPENNING_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKhhclhc3q32feengo84nnqwmdm]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKkaqa517cldv5ok4jsqu5vbn8v] FOREIGN KEY([AC_CUSTOMER_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKkaqa517cldv5ok4jsqu5vbn8v]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKl6erx0hnyenl6g0d3cq6bjpfo] FOREIGN KEY([AC_H_TAX_SALES_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKl6erx0hnyenl6g0d3cq6bjpfo]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKl8x49o6nmxvchcmbdf52ijve0] FOREIGN KEY([AC_JOURNAL_PURCHASES_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKl8x49o6nmxvchcmbdf52ijve0]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKm8wh03awo93i8en0eh8d6rt8u] FOREIGN KEY([AC_BANK_ACCOUNTING_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKm8wh03awo93i8en0eh8d6rt8u]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKn733smef7t1b0bjdakm888llm] FOREIGN KEY([AC_BALANCE_SHEET_CLOSING_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKn733smef7t1b0bjdakm888llm]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKnn6ji1j44oyyyjn6lwsy98op0] FOREIGN KEY([AC_JOURNAL_COFFER_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKnn6ji1j44oyyyjn6lwsy98op0]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKp8ma51h5ammthlk78kh5iqjcq] FOREIGN KEY([AC_H_TAX_PURCHASES_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKp8ma51h5ammthlk78kh5iqjcq]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKpffffsncm6krs3bcchlv0ucu8] FOREIGN KEY([AC_JOURNAL_SALES_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKpffffsncm6krs3bcchlv0ucu8]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKprl9ds5n9he28e1qaiodl64a7] FOREIGN KEY([AC_TAX_PURCHASES_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKprl9ds5n9he28e1qaiodl64a7]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKqr62vlmoyhr9c55pupsd5wdd9] FOREIGN KEY([AC_AMORTIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKqr62vlmoyhr9c55pupsd5wdd9]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKsbtxivlavwwf158tnnt2tadr5] FOREIGN KEY([AC_IMMOBILIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKsbtxivlavwwf158tnnt2tadr5]
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKsmsurstib1l1co4qd2e7u0kip] FOREIGN KEY([AC_TAX_SALES_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] CHECK CONSTRAINT [FKsmsurstib1l1co4qd2e7u0kip]
GO
ALTER TABLE [dbo].[T_AMORTIZATION_TABLE]  WITH CHECK ADD  CONSTRAINT [FKi2vyp945lsjugr03mokrsr189] FOREIGN KEY([AT_ASSETS_ID])
REFERENCES [dbo].[T_DEPRECIATION_ASSETS] ([DA_ID])
GO
ALTER TABLE [dbo].[T_AMORTIZATION_TABLE] CHECK CONSTRAINT [FKi2vyp945lsjugr03mokrsr189]
GO
ALTER TABLE [dbo].[T_AMORTIZATION_TABLE]  WITH CHECK ADD  CONSTRAINT [FKrl11pdf8bexolubchtaham4ku] FOREIGN KEY([AT_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_AMORTIZATION_TABLE] CHECK CONSTRAINT [FKrl11pdf8bexolubchtaham4ku]
GO
ALTER TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT]  WITH CHECK ADD  CONSTRAINT [FK2hpn7rsfl1jpfwg6s14b9n6ks] FOREIGN KEY([BRS_FISCAL_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT] CHECK CONSTRAINT [FK2hpn7rsfl1jpfwg6s14b9n6ks]
GO
ALTER TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT]  WITH CHECK ADD  CONSTRAINT [FKrxanq63f9tg8lbtiau9apf920] FOREIGN KEY([BRS_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_BANK_RECONCILIATION_STATEMENT] CHECK CONSTRAINT [FKrxanq63f9tg8lbtiau9apf920]
GO
ALTER TABLE [dbo].[T_BILL_DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FKrckobxhely953rrmaolcrf9sw] FOREIGN KEY([BD_DOCUMENT_ACCOUNT_ID])
REFERENCES [dbo].[T_DOCUMENT_ACCOUNT] ([DA_ID])
GO
ALTER TABLE [dbo].[T_BILL_DOCUMENT] CHECK CONSTRAINT [FKrckobxhely953rrmaolcrf9sw]
GO
ALTER TABLE [dbo].[T_CHART_ACCOUNTS]  WITH CHECK ADD  CONSTRAINT [FKsoq7gnlbny3j7vnldkdar1usk] FOREIGN KEY([CA_PARENT_ACCOUNT_ID])
REFERENCES [dbo].[T_CHART_ACCOUNTS] ([CA_ID])
GO
ALTER TABLE [dbo].[T_CHART_ACCOUNTS] CHECK CONSTRAINT [FKsoq7gnlbny3j7vnldkdar1usk]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS]  WITH CHECK ADD  CONSTRAINT [FKo9o3sslu7tom9bdggpmr5ucud] FOREIGN KEY([DA_IMMOBILIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS] CHECK CONSTRAINT [FKo9o3sslu7tom9bdggpmr5ucud]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS]  WITH CHECK ADD  CONSTRAINT [FKtgrgmd0x4b0jvp84uplfy3iny] FOREIGN KEY([DA_AMORTIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS] CHECK CONSTRAINT [FKtgrgmd0x4b0jvp84uplfy3iny]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK1uyq9i8cq13bf1eyxwml3m6an] FOREIGN KEY([DC_IMMOBILIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION] CHECK CONSTRAINT [FK1uyq9i8cq13bf1eyxwml3m6an]
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FKf5b1th46ukiayvfbbtvuiu6du] FOREIGN KEY([DC_AMORTIZATION_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_DEPRECIATION_ASSETS_CONFIGURATION] CHECK CONSTRAINT [FKf5b1th46ukiayvfbbtvuiu6du]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FKk9wcawb40utx3sch0281cbgnv] FOREIGN KEY([DA_FISCAL_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT] CHECK CONSTRAINT [FKk9wcawb40utx3sch0281cbgnv]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FKqk3lygkiyuag7x8afclfsr5m7] FOREIGN KEY([DA_JOURNAL_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT] CHECK CONSTRAINT [FKqk3lygkiyuag7x8afclfsr5m7]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_ATTACHEMENT]  WITH CHECK ADD  CONSTRAINT [FKkq8y6uqygsa6f6woqdb3eu769] FOREIGN KEY([DAA_DOCUMENT_ACCOUNT_ID])
REFERENCES [dbo].[T_DOCUMENT_ACCOUNT] ([DA_ID])
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_ATTACHEMENT] CHECK CONSTRAINT [FKkq8y6uqygsa6f6woqdb3eu769]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE]  WITH CHECK ADD  CONSTRAINT [FKaordevhtrvgsh3orgslajnj53] FOREIGN KEY([DAL_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE] CHECK CONSTRAINT [FKaordevhtrvgsh3orgslajnj53]
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE]  WITH CHECK ADD  CONSTRAINT [FKqi45g3kurv6h8tl96wt9360id] FOREIGN KEY([DAL_DOCUMENT_ACCOUNT_ID])
REFERENCES [dbo].[T_DOCUMENT_ACCOUNT] ([DA_ID])
GO
ALTER TABLE [dbo].[T_DOCUMENT_ACCOUNT_LINE] CHECK CONSTRAINT [FKqi45g3kurv6h8tl96wt9360id]
GO
ALTER TABLE [dbo].[T_FISCAL_YEAR_CLOSED_PERIODS]  WITH CHECK ADD  CONSTRAINT [FKdt90755xx2l5rw8y6isg3er2b] FOREIGN KEY([FYC_FISCAL_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_FISCAL_YEAR_CLOSED_PERIODS] CHECK CONSTRAINT [FKdt90755xx2l5rw8y6isg3er2b]
GO
ALTER TABLE [dbo].[T_GENERIC_ACCOUNT_RELATION]  WITH CHECK ADD  CONSTRAINT [FKb65q9lc2dmnaco14w6ogc1aog] FOREIGN KEY([GAR_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_GENERIC_ACCOUNT_RELATION] CHECK CONSTRAINT [FKb65q9lc2dmnaco14w6ogc1aog]
GO
ALTER TABLE [dbo].[T_REPORT_LINE]  WITH CHECK ADD  CONSTRAINT [FKerctrviywsrccrrn7lga8dq8b] FOREIGN KEY([RL_FISCAL_YEAR_ID])
REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_REPORT_LINE] CHECK CONSTRAINT [FKerctrviywsrccrrn7lga8dq8b]
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING]  WITH CHECK ADD  CONSTRAINT [FKsbqxyppac9w1ews0ar34ki053] FOREIGN KEY([TA_JOURNAL_ID])
REFERENCES [dbo].[T_JOURNAL] ([JN_ID])
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING] CHECK CONSTRAINT [FKsbqxyppac9w1ews0ar34ki053]
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK7akob5pvfsu5q35piga8xsmll] FOREIGN KEY([TAD_TEMPLATE_ACCOUNTING_ID])
REFERENCES [dbo].[T_TEMPLATE_ACCOUNTING] ([TA_ID])
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS] CHECK CONSTRAINT [FK7akob5pvfsu5q35piga8xsmll]
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS]  WITH CHECK ADD  CONSTRAINT [FKn4fevm4tuhdhyvgrdth3qberx] FOREIGN KEY([TAD_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[T_TEMPLATE_ACCOUNTING_DETAILS] CHECK CONSTRAINT [FKn4fevm4tuhdhyvgrdth3qberx]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_BANK]  WITH CHECK ADD  CONSTRAINT [FK_56h8osuqmvvxceboijjf07la] FOREIGN KEY([GAR_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_BANK] CHECK CONSTRAINT [FK_56h8osuqmvvxceboijjf07la]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_COFFER]  WITH CHECK ADD  CONSTRAINT [FK_s2q1jjq9fif5xthgwq6dr55rq] FOREIGN KEY([GAR_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_COFFER] CHECK CONSTRAINT [FK_s2q1jjq9fif5xthgwq6dr55rq]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_kk8tt1gulhmsqvm8auvoyj8tl] FOREIGN KEY([GAR_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_CUSTOMER] CHECK CONSTRAINT [FK_kk8tt1gulhmsqvm8auvoyj8tl]
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_SUPPLIER]  WITH CHECK ADD  CONSTRAINT [FK_krbbdhla507uqqwqyk7o45004] FOREIGN KEY([GAR_ACCOUNT_ID])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_ACCOUNT_SUPPLIER] CHECK CONSTRAINT [FK_krbbdhla507uqqwqyk7o45004]
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK4ks923jgiqrb11o1ipgklrpmi] FOREIGN KEY([PA_TAX_SALES_ACCOUNT])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT] CHECK CONSTRAINT [FK4ks923jgiqrb11o1ipgklrpmi]
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK5f9ioo2wxj6yi01nrrw3v7sgp] FOREIGN KEY([PA_TAX_PURCHASES_ACCOUNT])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT] CHECK CONSTRAINT [FK5f9ioo2wxj6yi01nrrw3v7sgp]
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK6tikp9qiwe4so8uha9dt3c5fy] FOREIGN KEY([PA_HTAX_SALES_ACCOUNT])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT] CHECK CONSTRAINT [FK6tikp9qiwe4so8uha9dt3c5fy]
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FKrnn26nxcn8q6un5m5itohtbmf] FOREIGN KEY([PA_HTAX_PURCHASES_ACCOUNT])
REFERENCES [dbo].[T_ACCOUNT] ([AC_ID])
GO
ALTER TABLE [dbo].[TJ_PAYMENT_ACCOUNT] CHECK CONSTRAINT [FKrnn26nxcn8q6un5m5itohtbmf]
GO
