SET IDENTITY_INSERT [dbo].[T_ACCOUNTING_CONFIGURATION] ON

ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] DROP CONSTRAINT FKfq5lmjce8vfsg4f1dh07ehshb;

ALTER TABLE [dbo].[T_ACCOUNTING_CONFIGURATION] DROP COLUMN [AC_CURRENT_FISCAL_YEAR_ID];
 	
SET IDENTITY_INSERT [dbo].[T_ACCOUNTING_CONFIGURATION] OFF

 