
UPDATE [dbo].[T_ACCOUNTING_CONFIGURATION]
   SET 
      [AC_INTANGIBLE_AMORTIZATION_ACCOUNT_ID] = 86,
      [AC_INTANGIBLE_IMMOBILIZATION_ACCOUNT_ID] = 338
 WHERE [AC_IS_DELETED] = 0;

exec SP_RENAME '[dbo].[T_ACCOUNTING_CONFIGURATION].[AC_AMORTIZATION_ACCOUNT_ID]', 'AC_TANGIBLE_AMORTIZATION_ACCOUNT_ID', 'COLUMN'
exec SP_RENAME '[dbo].[T_ACCOUNTING_CONFIGURATION].[AC_IMMOBILIZATION_ACCOUNT_ID]', 'AC_TANGIBLE_IMMOBILIZATION_ACCOUNT_ID', 'COLUMN'

