SET IDENTITY_INSERT [dbo].[T_STANDARD_REPORT_LINE] ON
ALTER TABLE [dbo].[T_STANDARD_REPORT_LINE]
    ADD [SRL_IS_TOTAL] [bit] NOT NULL default 0;
SET IDENTITY_INSERT [dbo].[T_STANDARD_REPORT_LINE] OFF

SET IDENTITY_INSERT [dbo].[T_REPORT_LINE] ON
ALTER TABLE [dbo].[T_REPORT_LINE]
    ADD [RL_IS_TOTAL] [bit] NOT NULL default 0;
SET IDENTITY_INSERT [dbo].[T_REPORT_LINE] OFF
