GO
/****** Object:  Table [dbo].[T_USER_PREFERENCE]    Script Date: 11/12/2020 20:11:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_USER_PREFERENCE](
          [UP_ID] [bigint] IDENTITY(1,1) NOT NULL,
          [UP_DELETED_TOKEN] [binary](255) NULL,
          [UP_IS_DELETED] [bit] NULL,
          [UP_USER_EMAIL] [varchar](255) NULL,
          [UP_CURRENT_FISCAL_YEAR_ID] [bigint] NULL,
          PRIMARY KEY CLUSTERED
              (
               [UP_ID] ASC
                  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
          CONSTRAINT [UKbo6rmb3lwdeb7o08wk0o6gggg] UNIQUE NONCLUSTERED
              (
               [UP_USER_EMAIL] ASC
                  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_USER_PREFERENCE] ADD  DEFAULT ((0)) FOR [UP_IS_DELETED]
GO
ALTER TABLE [dbo].[T_USER_PREFERENCE]  WITH CHECK ADD  CONSTRAINT [FK169pm5dn4r61i6mw4kpjo0929] FOREIGN KEY([UP_CURRENT_FISCAL_YEAR_ID])
    REFERENCES [dbo].[T_FISCAL_YEAR] ([FY_ID])
GO
ALTER TABLE [dbo].[T_USER_PREFERENCE] CHECK CONSTRAINT [FK169pm5dn4r61i6mw4kpjo0929]
GO
