SET IDENTITY_INSERT [dbo].[T_ACCOUNTING_CONFIGURATION] ON

UPDATE [dbo].[T_ACCOUNTING_CONFIGURATION]
   SET 
      [AC_FODEC_PURCHASES_ACCOUNT_ID] = 390,
      [AC_FODEC_SALES_ACCOUNT_ID] = 549
 WHERE [AC_IS_DELETED] = 0;
 
 SET IDENTITY_INSERT [dbo].[T_ACCOUNTING_CONFIGURATION] OFF
 
 	